version: "3.8"
services:
  dev_db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./init-db.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
